2018-03-28 16:56:14.038600: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
2018-03-28 16:56:14.317178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:01:00.0
totalMemory: 11.90GiB freeMemory: 10.61GiB
2018-03-28 16:56:14.317215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-28 16:56:14.614202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10271 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0, compute capability: 6.1)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
host_positive_prediction (65, 65, 1) [[[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]]

 ..., 
 [[ 0.49850366]
  [ 0.49850366]
  [ 0.46578726]
  ..., 
  [ 0.48781765]
  [ 0.55048591]
  [ 0.48004633]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49420872]
  ..., 
  [ 0.44810489]
  [ 0.5090524 ]
  [ 0.48789817]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.68487924]
  ..., 
  [ 0.63634348]
  [ 0.47160745]
  [ 0.49636647]]]
host_negative_prediction (65, 65, 1) [[[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]]

 ..., 
 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.45195672]
  [ 0.63179106]
  [ 0.45066237]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.49236226]
  [ 0.52688533]
  [ 0.47130829]]

 [[ 0.49850366]
  [ 0.49850366]
  [ 0.49850366]
  ..., 
  [ 0.75189525]
  [ 0.42859918]
  [ 0.49386907]]]
ncs_positive_prediction (274625,) [  4.98535156e-01   4.98535156e-01   4.98535156e-01 ...,  -2.31250000e+00
  -1.00076199e-04  -8.67247581e-05]
ncs_negative_prediction (274625,) [  4.98535156e-01   4.98535156e-01   4.98535156e-01 ...,  -2.31250000e+00
  -1.00076199e-04  -8.67247581e-05]
Traceback (most recent call last):
  File "./compare_inference_on_host_and_ncs.py", line 58, in <module>
    ncs_positive_prediction.shape))
Exception: shape mismatch between host [(65, 65, 1)] and ncs [(274625,)]
